export enum StackWidgetReference {
  attendance = 'attendance',
  attendances = 'attendances',
  billSetup = 'billSetup',
  caseParty = 'caseParty',
  chronology = 'chronology',
  chronologyStep = 'chronologyStep',
  confirm = 'confirm',
  correspondenceCounter = 'correspondenceCounter',
  counsel = 'counsel',
  counsels = 'counsels',
  coverSheetDetails = 'coverSheetDetails',
  coverSheetItem = 'coverSheetItem',
  coverSheets = 'coverSheets',
  disbursement = 'disbursement',
  disbursements = 'disbursements',
  documents = 'documents',
  documentsItem = 'documentsItem',
  enhancement = 'enhancement',
  enhancements = 'enhancements',
  export = 'export',
  feeEarner = 'feeEarner',
  narrative = 'narrative',
  otherDisbursements = 'otherDisbursements',
  otherWork = 'otherWork',
  part = 'part',
  parties = 'parties',
  parts = 'parts',
  party = 'party',
  rate = 'rate',
  rateGroup = 'rateGroup',
  rates = 'rates',
  settings = 'settings',
  solicitor = 'solicitor',
  solicitorLookup = 'solicitorLookup',
  successFee = 'successFee',
  successFees = 'successFees',
  textReplacement = 'textReplacement',
  textReplacements = 'textReplacements',
}

export const PART_SELECTOR_REQUIRED_STACK_WIDGET_REFERENCES: StackWidgetReference[] =
  [
    StackWidgetReference.chronology,
    StackWidgetReference.documents,
    StackWidgetReference.otherDisbursements,
    StackWidgetReference.otherWork,
    StackWidgetReference.parties,
  ];

export const FEE_EARNER_SELECTOR_REQUIRED_STACK_WIDGET_REFERENCES: StackWidgetReference[] =
  [StackWidgetReference.parties];

export const PART_QUICK_LINKS_REQUIRED_STACK_WIDGET_REFERENCES: StackWidgetReference[] =
  [
    StackWidgetReference.chronology,
    StackWidgetReference.parties,
    StackWidgetReference.documents,
  ];

export const STACK_WIDGET_REFERENCE_NAME_MAP: {
  [key in StackWidgetReference]: string;
} = {
  [StackWidgetReference.attendance]: 'Attendance',
  [StackWidgetReference.attendances]: 'Attendances',
  [StackWidgetReference.billSetup]: 'Bill setup',
  [StackWidgetReference.caseParty]: 'Case party',
  [StackWidgetReference.chronologyStep]: 'Chronology step',
  [StackWidgetReference.chronology]: 'Chronology',
  [StackWidgetReference.confirm]: 'Confirm',
  [StackWidgetReference.correspondenceCounter]: 'Correspondences',
  [StackWidgetReference.counsel]: 'Counsel',
  [StackWidgetReference.counsels]: 'Counsels',
  [StackWidgetReference.coverSheetDetails]: 'Cover sheet details',
  [StackWidgetReference.coverSheetItem]: 'Cover sheet item',
  [StackWidgetReference.coverSheets]: 'Cover sheets',
  [StackWidgetReference.disbursement]: 'Disbursement',
  [StackWidgetReference.disbursements]: 'Disbursements',
  [StackWidgetReference.documentsItem]: 'Documents item',
  [StackWidgetReference.documents]: 'Documents',
  [StackWidgetReference.enhancement]: 'Enhancement',
  [StackWidgetReference.enhancements]: 'Enhancements',
  [StackWidgetReference.export]: 'Export',
  [StackWidgetReference.feeEarner]: 'Fee earner',
  [StackWidgetReference.narrative]: 'Narrative',
  [StackWidgetReference.otherDisbursements]: 'Other disbursements',
  [StackWidgetReference.otherWork]: 'Other work',
  [StackWidgetReference.part]: 'Part',
  [StackWidgetReference.parties]: 'Parties',
  [StackWidgetReference.parts]: 'Parts',
  [StackWidgetReference.party]: 'Party',
  [StackWidgetReference.rateGroup]: 'Rate group',
  [StackWidgetReference.rate]: 'Rate',
  [StackWidgetReference.rates]: 'Rates',
  [StackWidgetReference.settings]: 'Settings',
  [StackWidgetReference.solicitor]: 'Solicitor',
  [StackWidgetReference.solicitorLookup]: 'Solicitor lookup',
  [StackWidgetReference.successFee]: 'Success fee',
  [StackWidgetReference.successFees]: 'Success fees',
  [StackWidgetReference.textReplacement]: 'Text replacement',
  [StackWidgetReference.textReplacements]: 'Text replacements',
};
